### ISSUE TITLE
this is not Issues but help

### ISSUE THREAD

**Issue by ghost** [prikhi/awesome-config#1]
how ı use your settings sorry my english so bad
and yes I'm turkish
ı'm idiot so how ı use your settings

**Comment by prikhi** [comment]
Hi, this is very old. I've switch to `xmonad` now. I don't know how it'll work with the latest version of awesome, but you can try to clone the repository into `~/.config/awesome`:

```sh
git clone --recursive-submodules https://github.com/prikhi/awesome-config.git ~/.config/awesome
cd ~/.config/awesome
```

And then restart awesome to see if it works...

**Comment by prikhi** [comment]
The majority of the configuration lives here:
https://github.com/prikhi/awesome-config/blob/master/rc.lua

The submodules are dependencies that are used by that config.

The colors & default background live here:
https://github.com/prikhi/awesome-config/blob/master/themes/molokai/theme.lua

Alternatively, check out the repository I based my config off of:
https://github.com/lcpz/awesome-copycats

The theme is "powerarrow-dark"
